[build]
  command = "cd ui/whiteboard-collab && npm install && npm run build"
  publish = "ui/whiteboard-collab/build"

[build.environment]
  NODE_ENV = "production"

[dev]
  command = "cd server && npm run dev "
  publish = "ui/whiteboard-collab/build"
  functions = "server/functions"